### ISSUE TITLE
vector<bool> should be used in tilelink mask_

### ISSUE THREAD

**Issue by dingiso** [sparcians/stf_lib#7]
After reading the codes and comments in `tilelink.hpp`, it seems like the program only uses the first bit in mask_ , so I think the type of mask_ should be vector<bool>.

**Comment by bdutro** [comment]
The implementation of `std::vector<bool>` depends on the compiler and platform. Many implementations pack/unpack the bits into an underlying integer storage, which imposes a performance penalty for a relatively minor reduction in runtime memory usage. We've opted for the simpler `vector<uint8_t>` implementation here for to keep performance predictable, and the memory overhead should be minor since TileLink mask values are relatively small.
